### ISSUE TITLE
Inconsistent licensing

### ISSUE THREAD

**Issue by akadusei** [shinzlet/phreak#5]
License in `shard.yml` says "GNU GPL v3"
https://github.com/shinzlet/phreak/blob/07e9e686d0bbe8a86f727c849a86b9502c92ee3f/shard.yml#L13

`LICENSE` file in the project's root is "MIT"
https://github.com/shinzlet/phreak/blob/07e9e686d0bbe8a86f727c849a86b9502c92ee3f/LICENSE#L1

**Comment by shinzlet** [comment]
Good catch, thanks! In earlier versions I was using a more copyleft licence, but I had a change of heart. Seems I missed that text, though. I'll fix it after work today.

**Comment by shinzlet** [comment]
Fixed in fe432f834290081c8709607118a79944030c3192
